debug: no
usePID: yes
pidName: PID
timeout: 21600
server_port: 5500
xpertTZ: America/Sao_Paulo
RCAuthApi: https://redcap.ctsc.weill.cornell.edu/redcap_protocols/api/
RCAuthPID: '5464'
RCAuthApiKey: ~
RCPIDApi: https://redcap.ctsc.weill.cornell.edu/redcap_protocols/api/
RCPIDApiKey: ~
RCCRFApi: https://redcap.ctsc.weill.cornell.edu/redcap_protocols/api/
RCCRFApiKey: ~
xpert:
  '16':
    use: yes
    ct: 40
  18_45:
    use: yes
    ct: 32
  P3:
    use: yes
    ct: 30
  P4:
    use: no
    ct: ''
  P5:
    use: no
    ct: ''
modules:
  auth: RCAuth
  pid: RCPID
  crf: RCCRF
